spring.application.name=FallPreventionBE
spring.datasource.url=jdbc:postgresql://localhost/fallpreventiondb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=512MB