spring.application.name=FallPreventionBE


# Porta do Servidor (Aquela que você configurou no Railway)
server.port=8080

# Conexão dinâmica com o PostgreSQL do Railway
# O Railway preenche o ${PGHOST}, ${PGPORT}, etc., sozinho na nuvem!
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Configurações do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
